{{- if $.Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-mock-configmap
  namespace: {{ .Release.Namespace }}
data: 
  ASPNETCORE_ENVIRONMENT: Development
  SERVER_OPTIONS_INLINE: |
    {
      "AccessTokenJwtType": "JWT",
      "Discovery": {
        "ShowKeySet": true
      },
      "Authentication": {
        "CookieSameSiteMode": "Lax",
        "CheckSessionCookieSameSiteMode": "Lax"
      }
    }
  LOGIN_OPTIONS_INLINE: |
    {
      "AllowRememberLogin": false
    }
  LOGOUT_OPTIONS_INLINE: |
    {
      "AutomaticRedirectAfterSignOut": true
    }
  API_SCOPES_INLINE: |
    - Name: some-app-scope-1
    - Name: some-app-scope-2
  API_RESOURCES_INLINE: |
    - Name: some-app
      Scopes: 
        - some-app-scope-1
        - some-app-scope-2
  USERS_CONFIGURATION_INLINE: |
    [
      {
        "SubjectId":"1",
        "Username":"User1",
        "Password":"pwd",
        "Claims": [
          {
            "Type": "name",
            "Value": "Sam Tailor",
            "ValueType": "string"
          },
          {
            "Type": "email",
            "Value": "sam.tailor@gmail.com",
            "ValueType": "string"
          },
          {
            "Type": "some-api-resource-claim",
            "Value": "Sam's Api Resource Custom Claim",
            "ValueType": "string"
          },
          {
            "Type": "some-api-scope-claim",
            "Value": "Sam's Api Scope Custom Claim",
            "ValueType": "string"
          },
          {
            "Type": "some-identity-resource-claim",
            "Value": "Sam's Identity Resource Custom Claim",
            "ValueType": "string"
          }
        ]
      }
    ]
  CLIENTS_CONFIGURATION_INLINE: |
    [
      {
        "ClientId": "implicit-mock-client",
        "Description": "Client for implicit flow",
        "AllowedGrantTypes": ["implicit"],
        "AllowAccessTokensViaBrowser": true,
        "RedirectUris": ["http://localhost:3000/auth/oidc", "http://localhost:4004/auth/oidc"],
        "AllowedScopes": ["openid", "profile", "email"],
        "IdentityTokenLifetime": 3600,
        "AccessTokenLifetime": 3600
      },
      {
        "ClientId": "client-credentials-mock-client",
        "ClientSecrets": ["client-credentials-mock-client-secret"],
        "Description": "Client for client credentials flow",
        "AllowedGrantTypes": ["client_credentials"],
        "AllowedScopes": ["some-app-scope-1"],
        "ClientClaimsPrefix": "",
        "Claims": [
          {
            "Type": "string_claim",
            "Value": "string_claim_value",
            "ValueType": "string"
          },
          {
            "Type": "json_claim",
            "Value": "[\"value1\", \"value2\"]",
            "ValueType": "json"
          }
        ]
      }
    ]
  ASPNET_SERVICES_OPTIONS_INLINE: |
    {
      "ForwardedHeadersOptions": {
        "ForwardedHeaders" : "All"
      }
    }
{{- end }}
