apiVersion: v2
name: oidc-mock
description: Mock OIDC for Developer Environment
type: application

version: 0.1.0
dependencies:
  - name: common
    version: 2.23.0
    repository: oci://docker.io/bitnamicharts
